language: generic
sudo: required
serices:
    - docker

before_install:
    - docker build -t durganz/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true durganz/docker-react npm run test
